name: Fill some extra info about map
description: Enter missing or correct existing info about map
title: Enter map name here
labels:
- map-data
body:
- type: textarea
  id: issue_description
  attributes:
    label: Issue description
    description: Write reasoning for this change below
    placeholder: Reasoning for the change, e.g data are missing or I disagree with
      X or Y and here is why etc. You can also add extra info not contained in form
      here for example boss notes or notes for any other fields.
  validations:
    required: true
- type: dropdown
  id: map_name
  attributes:
    label: Map name
    description: Select map from dropdown or leave at **None** if title is properly
      filled.
    options:
    - Academy
    - Acid Caverns
    - Acton's Nightmare
    - Alleyways
    - Altered Distant Memory
    - Arachnid Nest
    - Arachnid Tomb
    - Arcade
    - Arena
    - Atoll
    - Augmented Distant Memory
    - Barrows
    - Basilica
    - Bazaar
    - Beach
    - Bog
    - Bone Crypt
    - Caer Blaidd, Wolfpack's Den
    - Cage
    - Caldera
    - Carcass
    - Castle Ruins
    - Cells
    - Cemetery
    - Channel
    - Chateau
    - City Square
    - Cold River
    - Colonnade
    - Colosseum
    - Cortex
    - Courthouse
    - Courtyard
    - Coves
    - Crimson Temple
    - Cursed Crypt
    - Dark Forest
    - Death and Taxes
    - Doryani's Machinarium
    - Dunes
    - Dungeon
    - Estuary
    - Excavation
    - Factory
    - Flooded Mine
    - Forge of the Phoenix
    - Forking River
    - Frozen Cabins
    - Fungal Hollow
    - Geode
    - Glacier
    - Grave Trough
    - Graveyard
    - Hall of Grandmasters
    - Hallowed Ground
    - Haunted Mansion
    - Iceberg
    - Infested Valley
    - Infused Beachhead
    - Ivory Temple
    - Lair of the Hydra
    - Lava Chamber
    - Lava Lake
    - Leyline
    - Lookout
    - "Maelstr\xF6m of Chaos"
    - Malformation
    - Mao Kun
    - Mausoleum
    - Maze
    - Maze of the Minotaur
    - Mesa
    - Mineral Pools
    - Moon Temple
    - Mud Geyser
    - Museum
    - Necropolis
    - Oba's Cursed Trove
    - Olmec's Sanctum
    - Orchard
    - Overgrown Shrine
    - Palace
    - Pen
    - Phantasmagoria
    - Pier
    - Pillars of Arun
    - Pit
    - Pit of the Chimera
    - Plateau
    - Poorjoy's Asylum
    - Port
    - Precinct
    - Primordial Blocks
    - Primordial Pool
    - Promenade
    - Racecourse
    - Reef
    - Replica Cortex
    - Replica Pillars of Arun
    - Replica Poorjoy's Asylum
    - Residence
    - Rewritten Distant Memory
    - Shore
    - Siege
    - Silo
    - Spider Forest
    - Stagnation
    - Strand
    - Sulphur Vents
    - Summit
    - Sunken City
    - Temple
    - Terrace
    - The Beachhead
    - The Coward's Trial
    - The Putrid Cloister
    - The Tower of Ordeals
    - The Twilight Temple
    - The Vinktar Square
    - Thicket
    - Tower
    - Tropical Island
    - Twisted Distant Memory
    - Underground River
    - Underground Sea
    - Untainted Paradise
    - Vaal Pyramid
    - Vaal Temple
    - Vault
    - Vaults of Atziri
    - Volcano
    - Wasteland
    - Waterways
    - Whakawairua Tuahu
    - Wharf
  validations:
    required: false
- type: textarea
  id: map_image
  attributes:
    label: Map image
    description: Map layout image. If you dont have one simply leave empty.
    placeholder: Upload layout image here
  validations:
    required: false
- type: dropdown
  id: layout_rating
  attributes:
    label: Layout rating
    description: Map layout rating. If you dont know simply leave at None.
    options:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
  validations:
    required: false
- type: dropdown
  id: density_rating
  attributes:
    label: Density rating
    description: Map density rating. If you dont know simply leave at None.
    options:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
  validations:
    required: false
- type: dropdown
  id: boss_rating
  attributes:
    label: Boss rating
    description: Map boss rating. If you dont know simply leave at None.
    options:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
  validations:
    required: false
- type: checkboxes
  id: layout
  attributes:
    label: Layout
    description: Map layout metadata. If you dont know simply leave the box unchecked.
    options:
    - label: '**League mechanics** - If map is good for league mechanics that require
        some space (Breach, Legion)'
    - label: '**Delirium mirror** - If you can hold delirium mirror through whole
        map or delirium mirror gets good value in it'
    - label: '**Outdoors** - If map is outdoors or indoors (Dunes vs Cells for example)'
    - label: '**Linear** - If map is linear instead of having multiple paths to take.
        Map counts as linear even if the line goes in circle'
    - label: '**Few obstacles** - If map does not have a lot of obstacles (so for
        example is good for shield charging around)'
  validations:
    required: false
- type: checkboxes
  id: boss
  attributes:
    label: Boss
    description: Map boss metadata. If you dont know simply leave the box unchecked.
    options:
    - label: '**Not spawned** - If boss is not spawned on entering the map (important
        for Altar farming, can be verified by checking for boss altars spawning or
        not)'
    - label: '**Rushable** - If boss is close to map start or can be rushed quickly
        and reliably, a lot quicker than completing whole map'
    - label: '**Phases** - If boss has hard phases that force you to wait (delay on
        initial boss spawn counts too)'
    - label: '**Soft phases** - If boss has soft phases that can be bypassed with
        DPS (teleports at certain threshold, heals, partial damage reduction)'
    - label: '**Separated** - If boss room is separated from rest of the map'
  validations:
    required: false
