name: Fill some extra info about map
description: Enter missing or correct existing info about map
title: Enter map name here
labels:
- map-data
body:
- type: textarea
  id: issue_description
  attributes:
    label: Issue description
    description: Write reasoning for this change below
    placeholder: Reasoning for the change, e.g data are missing or I disagree with
      X or Y and here is why etc. You can also add extra info not contained in form
      here for example boss notes or notes for any other fields.
  validations:
    required: true
- type: dropdown
  id: map_name
  attributes:
    label: Map name
    description: Select map from dropdown or leave at **None** if title is properly
      filled.
    options:
    - Abandoned Port
    - Abomination
    - Absence of Mercy and Empathy
    - Absence of Patience and Wisdom
    - Absence of Symmetry and Harmony
    - Absence of Value and Meaning
    - Academy
    - Acid Caverns
    - Acton's Nightmare
    - Alleyways
    - Altered Distant Memory
    - Ancient City
    - Arachnid Nest
    - Arachnid Tomb
    - Arcade
    - Arena
    - Arid Lake
    - Armoury
    - Arsenal
    - Ashen Wood
    - Atoll
    - Augmented Distant Memory
    - Barrows
    - Basilica
    - Bazaar
    - Beach
    - Belfry
    - Bog
    - Bone Crypt
    - Bramble Valley
    - Burial Chambers
    - Caer Blaidd, Wolfpack's Den
    - Cage
    - Caldera
    - Canyon
    - Carcass
    - Castle Ruins
    - Cells
    - Cemetery
    - Channel
    - Chateau
    - Chayula's Domain
    - Citadel
    - City Square
    - Cold River
    - Colonnade
    - Colosseum
    - Conservatory
    - Coral Ruins
    - Core
    - Cortex
    - Courthouse
    - Courtyard
    - Coves
    - Crater
    - Crimson Temple
    - Crimson Township
    - Crux of Nothingness
    - Crystal Ore
    - Cursed Crypt
    - Dark Forest
    - Death and Taxes
    - Defiled Cathedral
    - Desert
    - Desert Spring
    - Dig
    - Doryani's Machinarium
    - Dry Sea
    - Dunes
    - Dungeon
    - Esh's Domain
    - Estuary
    - Excavation
    - Eye of the Storm
    - Factory
    - Fields
    - Flooded Mine
    - Forbidden Woods
    - Forge of the Phoenix
    - Forking River
    - Fortress
    - Foundry
    - Frozen Cabins
    - Fungal Hollow
    - Gardens
    - Geode
    - Ghetto
    - Glacier
    - Grave Trough
    - Graveyard
    - Grotto
    - Hall of Grandmasters
    - Hallowed Ground
    - Haunted Mansion
    - Iceberg
    - Infested Valley
    - Infused Beachhead
    - Ivory Temple
    - Jungle Valley
    - Laboratory
    - Lair
    - Lair of the Hydra
    - Lava Chamber
    - Lava Lake
    - Leyline
    - Lighthouse
    - Lookout
    - "Maelstr\xF6m of Chaos"
    - Malformation
    - Mao Kun
    - Marshes
    - Mausoleum
    - Maze
    - Maze of the Minotaur
    - Mesa
    - Mineral Pools
    - Moon Temple
    - Mud Geyser
    - Museum
    - Necropolis
    - Oba's Cursed Trove
    - Olmec's Sanctum
    - Orchard
    - Overgrown Ruin
    - Overgrown Shrine
    - Palace
    - Park
    - Pen
    - Peninsula
    - Phantasmagoria
    - Pier
    - Pillars of Arun
    - Pit
    - Pit of the Chimera
    - Plateau
    - Plaza
    - Polaric Void
    - Poorjoy's Asylum
    - Port
    - Precinct
    - Primordial Blocks
    - Primordial Pool
    - Promenade
    - Racecourse
    - Ramparts
    - Reef
    - Relic Chambers
    - Residence
    - Rewritten Distant Memory
    - Sanctuary
    - Scriptorium
    - Seething Chyme
    - Sepulchre
    - Shipyard
    - Shore
    - Shrine
    - Siege
    - Silo
    - Spider Forest
    - Spider Lair
    - Stagnation
    - Starfall Crater
    - Strand
    - Sulphur Vents
    - Summit
    - Sunken City
    - Temple
    - Terrace
    - The Alluring Abyss
    - The Apex of Sacrifice
    - The Beachhead
    - The Coward's Trial
    - The Maven's Crucible
    - The Putrid Cloister
    - The Sacred Grove
    - The Shaper's Realm
    - The Temple of Atzoatl
    - The Tower of Ordeals
    - The Twilight Temple
    - The Vinktar Square
    - Thicket
    - Tower
    - Toxic Sewer
    - Trial of Burning Rage
    - Trial of Crippling Grief
    - Trial of Lingering Pain
    - Trial of Piercing Truth
    - Trial of Stinging Doubt
    - Trial of Swirling Fear
    - Tropical Island
    - Tul's Domain
    - Twisted Distant Memory
    - Underground River
    - Underground Sea
    - Untainted Paradise
    - Uul-Netol's Domain
    - Vaal Pyramid
    - Vaal Temple
    - Vault
    - Vaults of Atziri
    - Villa
    - Volcano
    - Waste Pool
    - Wasteland
    - Waterways
    - Whakawairua Tuahu
    - Wharf
    - Xoph's Domain
    - Ziggurat
  validations:
    required: false
- type: textarea
  id: map_image
  attributes:
    label: Map image
    description: Map layout image. If you dont have one simply leave empty.
    placeholder: Upload layout image here
  validations:
    required: false
- type: dropdown
  id: layout_rating
  attributes:
    label: Layout rating
    description: Map layout rating. If you dont know simply leave at None.
    options:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
  validations:
    required: false
- type: dropdown
  id: density_rating
  attributes:
    label: Density rating
    description: Map density rating. If you dont know simply leave at None.
    options:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
  validations:
    required: false
- type: dropdown
  id: boss_rating
  attributes:
    label: Boss rating
    description: Map boss rating. If you dont know simply leave at None.
    options:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
  validations:
    required: false
- type: checkboxes
  id: tags
  attributes:
    label: Tags
    description: Map tags metadata. If you dont know simply leave the box unchecked.
    options:
    - label: '**League mechanics** - If map is good for league mechanics that require
        some space (Breach, Legion)'
    - label: '**Delirium mirror** - If you can hold delirium mirror through whole
        map or delirium mirror gets good value in it'
    - label: '**Outdoors** - If map is outdoors or indoors (Dunes vs Cells for example)'
    - label: '**Linear** - If map is linear instead of having multiple paths to take.
        Map counts as linear even if the line goes in circle'
    - label: '**Few obstacles** - If map does not have a lot of obstacles (so for
        example is good for shield charging around)'
    - label: '**Boss Not spawned** - If boss is not spawned on entering the map (important
        for Altar farming, can be verified by checking for boss altars spawning or
        not)'
    - label: '**Boss Rushable** - If boss is close to map start or can be rushed quickly
        and reliably, a lot quicker than completing whole map'
    - label: '**Boss Phases** - If boss has hard phases that force you to wait (delay
        on initial boss spawn counts too)'
    - label: '**Boss Soft phases** - If boss has soft phases that can be bypassed
        with DPS (teleports at certain threshold, heals, partial damage reduction)'
    - label: '**Boss Separated** - If boss room is separated from rest of the map'
  validations:
    required: false
