name: Fill some extra info about map
description: Enter missing or correct existing info about map
title: '[Map] '
labels:
- map-data
body:
- type: dropdown
  id: map_name
  attributes:
    label: Map name
    description: Select map from dropdown.
    options:
    - Acton's Nightmare
    - Alleyways Map
    - Altered Distant Memory
    - Arachnid Nest Map
    - Arachnid Tomb Map
    - Arcade Map
    - Arid Lake Map
    - Armoury Map
    - Arsenal Map
    - Atoll Map
    - Augmented Distant Memory
    - Barrows Map
    - Beach Map
    - Belfry Map
    - Bone Crypt Map
    - Caer Blaidd, Wolfpack's Den
    - Caldera Map
    - Canyon Map
    - Castle Ruins Map
    - Cells Map
    - Cemetery Map
    - Chateau Map
    - City Square Map
    - Cold River Map
    - Colonnade Map
    - Colosseum Map
    - Conservatory Map
    - Coral Ruins Map
    - Core Map
    - Cortex
    - Courtyard Map
    - Coves Map
    - Crater Map
    - Crimson Temple Map
    - Crimson Township Map
    - Crystal Ore Map
    - Cursed Crypt Map
    - Death and Taxes
    - Defiled Cathedral Map
    - Desert Spring Map
    - Dig Map
    - Doryani's Machinarium
    - Dry Sea Map
    - Dunes Map
    - Dungeon Map
    - Excavation Map
    - Factory Map
    - Fields Map
    - Flooded Mine Map
    - Forbidden Woods Map
    - Forge of the Phoenix Map
    - Foundry Map
    - Frozen Cabins Map
    - Fungal Hollow Map
    - Geode Map
    - Grotto Map
    - Hall of Grandmasters
    - Hallowed Ground
    - Infested Valley Map
    - Infused Beachhead
    - Jungle Valley Map
    - Laboratory Map
    - Lair Map
    - Lair of the Hydra Map
    - Leyline Map
    - Lighthouse Map
    - "Maelstr\xF6m of Chaos"
    - Malformation Map
    - Mao Kun
    - Marshes Map
    - Maze Map
    - Maze of the Minotaur Map
    - Mineral Pools Map
    - Moon Temple Map
    - Museum Map
    - Necropolis Map
    - Oba's Cursed Trove
    - Olmec's Sanctum
    - Orchard Map
    - Overgrown Ruin Map
    - Overgrown Shrine Map
    - Phantasmagoria Map
    - Pier Map
    - Pillars of Arun
    - Pit Map
    - Pit of the Chimera Map
    - Plateau Map
    - Plaza Map
    - Poorjoy's Asylum
    - Port Map
    - Precinct Map
    - Primordial Blocks Map
    - Primordial Pool Map
    - Promenade Map
    - Racecourse Map
    - Ramparts Map
    - Relic Chambers Map
    - Replica Cortex
    - Replica Pillars of Arun
    - Replica Poorjoy's Asylum
    - Residence Map
    - Rewritten Distant Memory
    - Scriptorium Map
    - Shipyard Map
    - Shore Map
    - Shrine Map
    - Siege Map
    - Silo Map
    - Stagnation Map
    - Strand Map
    - Sulphur Vents Map
    - Temple Map
    - Terrace Map
    - The Beachhead
    - The Coward's Trial
    - The Putrid Cloister
    - The Tower of Ordeals
    - The Twilight Temple
    - The Vinktar Square
    - Thicket Map
    - Tower Map
    - Toxic Sewer Map
    - Tropical Island Map
    - Twisted Distant Memory
    - Underground River Map
    - Underground Sea Map
    - Untainted Paradise
    - Vaal Pyramid Map
    - Vaal Temple Map
    - Vaults of Atziri
    - Volcano Map
    - Waste Pool Map
    - Wasteland Map
    - Whakawairua Tuahu
    - Wharf Map
  validations:
    required: true
- type: textarea
  id: map_image
  attributes:
    label: Map image
    description: Map layout image. If you dont have one simply leave empty.
    placeholder: Upload layout image here
  validations:
    required: false
- type: dropdown
  id: layout_rating
  attributes:
    label: Layout rating
    description: Map layout rating. If you dont know simply leave at None.
    options:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
  validations:
    required: false
- type: dropdown
  id: density_rating
  attributes:
    label: Density rating
    description: Map density rating. If you dont know simply leave at None.
    options:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
  validations:
    required: false
- type: dropdown
  id: boss_rating
  attributes:
    label: Boss rating
    description: Map boss rating. If you dont know simply leave at None.
    options:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
  validations:
    required: false
- type: checkboxes
  id: layout
  attributes:
    label: Layout
    description: Map layout metadata. If you dont know simply leave the box unchecked.
    options:
    - label: '**League mechanics** - If map is good for league mechanics that require
        some space (Breach, Legion)'
    - label: '**Delirium mirror** - If you can hold delirium mirror through whole
        map or delirium mirror gets good value in it'
    - label: '**Outdoors** - If map is outdoors or indoors (Dunes vs Cells for example)'
    - label: '**Linear** - If map is linear instead of having multiple paths to take.
        Map counts as linear even if the line goes in circle'
    - label: '**Few obstacles** - If map does not have a lot of obstacles (so for
        example is good for shield charging around)'
  validations:
    required: false
- type: checkboxes
  id: boss
  attributes:
    label: Boss
    description: Map boss metadata. If you dont know simply leave the box unchecked.
    options:
    - label: '**Not spawned** - If boss is not spawned on entering the map (important
        for Altar farming, can be verified by checking for boss altars spawning or
        not)'
    - label: '**Rushable** - If boss is close to map start or can be rushed quickly
        and reliably, a lot quicker than completing whole map'
    - label: '**Phases** - If boss has hard phases that force you to wait (delay on
        initial boss spawn counts too)'
    - label: '**Soft phases** - If boss has soft phases that can be bypassed with
        DPS (teleports at certain threshold, heals, partial damage reduction)'
    - label: '**Separated** - If boss room is separated from rest of the map'
  validations:
    required: false
- type: textarea
  id: boss_notes
  attributes:
    label: Boss Notes
    description: Map boss notes. If there isn't anything to add simply leave empty.
  validations:
    required: false
