name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
defaults:
  run:
    working-directory: site
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy
        if: ${{ github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@v4

        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: site/build
          clean: true
          force: true
