name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup python
        if: ${{ github.event_name == 'push' }}
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install data dependencies
        if: ${{ github.event_name == 'push' }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: data

      - name: Build data
        if: ${{ github.event_name == 'push' }}
        run: python main.py cards,maps
        working-directory: data
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

      - name: Push data
        if: ${{ github.event_name == 'push' }}
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git commit -am "Update maps and cards"
          git push

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install site dependencies
        run: npm ci
        working-directory: site

      - name: Build site
        run: npm run build
        working-directory: site

      - name: Deploy site
        if: ${{ github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@v4

        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: site/build
          clean: true
          force: true
